(deftheme ate-light
	 "Custom theme by Andrew Erlanger.")

(defmacro face (name &rest settings)
  `''(,name ((t (:font ,myfont ,@settings)))))

(defmacro set-theme-faces ()
  `(custom-theme-set-faces
	'ate-light
	,(face default
		   :background "black"
		   :foreground "white")
	,(face bold
		   :inherit default)
	,(face error
		   :foreground "red"
		   :weight bold)
	,(face bold-italic
		   :weight bold
		   :slant italic)
;;; paren
	,(face show-paren-match :background "grey23")
;;; Info
	,(face Info-quoted)
	,(face dired-directory :foreground "magenta")
	,(face font-lock-builtin-face :inherit default :foreground "blue1")
	,(face font-lock-comment-face :inherit default :foreground "chartreuse")
	,(face font-lock-constant-face :inherit default :foreground "orange")
	,(face font-lock-doc-face :inherit default :foreground "green")
	,(face font-lock-function-name-face :inherit default :foreground "magenta")
	,(face font-lock-keyword-face :inherit default :foreground "cyan")
	,(face font-lock-preprocessor-face :inherit default)
	,(face font-lock-string-face :inherit default :foreground "wheat")
	,(face font-lock-type-face :inherit default :foreground "deep pink")
	,(face font-lock-variable-name-face :inherit default :foreground "yellow")
	,(face font-lock-warning-face :inherit default)
	,(face gnus-button :inherit button)
	,(face highlight :background "white" :foreground "black")
	,(face hl-line :background "grey25")
	,(face hl-paren-face :weight bold)
	,(face icomplete-first-match :foreground "deep sky blue" :weight bold)
	,(face lusty-file-face :foreground "SpringGreen1")
	,(face magit-header :box 1 :weight bold)
	,(face magit-section-title :inherit magit-header
		   :background "dark slate blue")
	,(face menu :background "gray30" :foreground "gray70")
	,(face region :background "grey" :foreground "black")
	,(face scroll-bar :background "gray20" :foreground "dark turquoise")
	,(face secondary-selection :background "green" :foreground "black")
	,(face show-paren-match :background "green")
	,(face show-paren-mismatch :background "red")
	,(face th-sentence-hl-face :weight bold)
	,(face window-number-face :foreground "red" :weight bold)
;;; whitespace
	,(face whitespace-line :background "grey" :foreground "black")
	,(face trailing-whitespace :background "white")
;;; ido
	,(face ido-first-match :inheit default
		   :foreground "turquoise"
		   :weight bold)
	,(face ido-only-match :foreground "medium spring green"
		   :weight bold)
	,(face ido-subdir :inherit dired-directory
		   :weight normal)
;;; Minibuffer and mode line
	,(face minibuffer-prompt :foreground "red")
	,(face mode-line :background "yellow"
		   :foreground "black")
	,(face mode-line-inactive :inherit mode-line
		   :background "grey"
		   :foreground "black")
;;; General outlining
	,(face outline-1 :foreground "red1")
	,(face outline-2 :foreground "orange1")
	,(face outline-3 :foreground "yellow1")
	,(face outline-4 :foreground "green")
	,(face outline-5 :foreground "medium spring green")
	,(face outline-6 :foreground "deep sky blue")
	,(face outline-7 :foreground "magenta")
	,(face outline-8 :foreground "DeepPink1")
;;; Org mode
	,(face org-default :inherit default)
	,(face org-hide :inherit mode-line-inactive)
	,(face org-level-1 :inherit outline-1)
	,(face org-level-2 :inherit outline-2)
	,(face org-level-3 :inherit outline-3)
	,(face org-level-4 :inherit outline-4)
	,(face org-level-5 :inherit outline-5)
	,(face org-level-6 :inherit outline-6)
	,(face org-level-7 :inherit outline-7)
	,(face org-level-8 :inherit outline-8)
	,(face org-special-keyword :inherit font-lock-keyword-face)
	,(face org-warning :foreground "red")
	,(face org-agenda-structure :foreground "blue")
	,(face org-agenda-calendar-event nil)
	,(face org-agenda-date :foreground "yellow")
	,(face org-agenda-date-today :foreground "magenta")
	,(face org-agenda-date-weekend :inherit org-agenda-date)
	,(face org-agenda-done :foreground "green")
	,(face org-agenda-restriction-lock :background "#FFB273")
	,(face org-agenda-dimmed-todo-face :foreground "blue")
	,(face org-date :foreground "magenta")
	,(face org-done :foreground "green")
	,(face org-drawer :foreground "#2A4480")
	,(face org-ellipsis :foreground "magenta")
	,(face org-footnote :foreground "white")
	,(face org-scheduled-previously :foreground "#FF7400")
	,(face org-tag :weight bold)
	,(face org-todo :foreground "red")
;;; Rainbow delimiter font locks
;;; Order generated by add-three transitive group action
;;; on Z/7Z to ensure neighboring colors contrast
	,(face rainbow-delimiters-depth-1-face :inherit outline-1)
	,(face rainbow-delimiters-depth-2-face :inherit outline-4)
	,(face rainbow-delimiters-depth-3-face :inherit outline-7)
	,(face rainbow-delimiters-depth-4-face :inherit outline-3)
	,(face rainbow-delimiters-depth-5-face :inherit outline-6)
	,(face rainbow-delimiters-depth-6-face :inherit outline-2)
	,(face rainbow-delimiters-depth-7-face :inherit outline-5)
	,(face rainbow-delimiters-depth-8-face :inherit outline-1)
	,(face rainbow-delimiters-depth-9-face :inherit outline-4)))

(set-theme-faces)

(provide-theme 'ate-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; ate-light-theme.el ends here
