(deftheme ate
  "Custom theme by Andrew Erlanger.")

(defmacro ate-theme|set-faces (&rest specs)
  `(apply #'custom-theme-set-faces
		  (cons 'ate
				(quote ,(mapcar (lambda (s) (list (car s)
												  (list (cons t
															  (cdr s)))))
								specs)))))

(ate-theme|set-faces
 (default
   :background "black"
   :foreground "white")
 (bold
  :inherit default)
 (error
  :foreground "red"
  :weight bold)
 (bold-italic
  :weight bold
  :slant italic)
;;; paren
 (show-paren-match :background "grey23")
;;; Info
 (Info-quoted)
 (dired-directory :foreground "magenta")
 (font-lock-builtin-face :inherit default :foreground "yellow")
 (font-lock-comment-face :inherit default :foreground "chartreuse")
 (font-lock-constant-face :inherit default :foreground "orange")
 (font-lock-doc-face :inherit default :foreground "green")
 (font-lock-function-name-face :inherit default :foreground "magenta")
 (font-lock-keyword-face :inherit default :foreground "cyan")
 (font-lock-preprocessor-face :inherit default)
 (font-lock-string-face :inherit default :foreground "wheat")
 (font-lock-type-face :inherit default :foreground "deep pink")
 (font-lock-variable-name-face :inherit default :foreground "yellow")
 (font-lock-warning-face :inherit default)
 (gnus-button :inherit button)
 (highlight :background "white" :foreground "black")
 (hl-line :background "grey25")
 (hl-paren-face :weight bold)
 (icomplete-first-match :foreground "deep sky blue" :weight bold)
 (lusty-file-face :foreground "SpringGreen1")
 (magit-header :box 1 :weight bold)
 (magit-section-title :inherit magit-header
					  :background "dark slate blue")
 (menu :background "grey30" :foreground "grey70")
 (region :background "grey" :foreground "black")
 (scroll-bar :background "gray20" :foreground "dark turquoise")
 (secondary-selection :background "green" :foreground "black")
 (show-paren-match :background "grey23")
 (show-paren-mismatch :background "red")
 (th-sentence-hl-face :weight bold)
 (window-number-face :foreground "red" :weight bold)
;;; whitespace
 (whitespace-line :background "grey" :foreground "black")
 (trailing-whitespace :background "white")
;;; ido
 (ido-first-match :inheit default
				  :foreground "turquoise"
				  :weight bold)
 (ido-only-match :foreground "medium spring green"
				 :weight bold)
 (ido-subdir :inherit dired-directory
			 :weight normal)
;;; Minibuffer and mode line
 (minibuffer-prompt :foreground "red")
 (mode-line :background "yellow"
			:foreground "black")
 (mode-line-inactive :inherit mode-line
					 :background "grey"
					 :foreground "black")
;;; General outlining
 (outline-1 :foreground "red1")
 (outline-2 :foreground "orange1")
 (outline-3 :foreground "yellow1")
 (outline-4 :foreground "green")
 (outline-5 :foreground "medium spring green")
 (outline-6 :foreground "deep sky blue")
 (outline-7 :foreground "magenta")
 (outline-8 :foreground "DeepPink1")
;;; Org mode
 (org-default :inherit default)
 (org-hide :inherit default)
 (org-level-1 :inherit outline-1)
 (org-level-2 :inherit outline-2)
 (org-level-3 :inherit outline-3)
 (org-level-4 :inherit outline-4)
 (org-level-5 :inherit outline-5)
 (org-level-6 :inherit outline-6)
 (org-level-7 :inherit outline-7)
 (org-level-8 :inherit outline-8)
 (org-special-keyword :inherit font-lock-keyword-face)
 (org-warning :foreground "red")
 (org-agenda-structure :foreground "blue")
 (org-agenda-calendar-event nil)
 (org-agenda-date :foreground "yellow")
 (org-agenda-date-today :foreground "magenta")
 (org-agenda-date-weekend :inherit org-agenda-date)
 (org-agenda-done :foreground "green")
 (org-agenda-restriction-lock :background "#FFB273")
 (org-agenda-dimmed-todo-face :foreground "blue")
 (org-date :foreground "magenta")
 (org-done :foreground "green")
 (org-drawer :foreground "#2A4480")
 (org-ellipsis :foreground "magenta")
 (org-footnote :foreground "white")
 (org-scheduled-previously :foreground "#FF7400")
 (org-tag :weight bold)
 (org-todo :foreground "red")
;;; Rainbow delimiter font locks
;;; Order generated by add-three transitive group action
;;; on Z/7Z to ensure neighboring colors contrast
 (rainbow-delimiters-depth-1-face :inherit outline-1)
 (rainbow-delimiters-depth-2-face :inherit outline-4)
 (rainbow-delimiters-depth-3-face :inherit outline-7)
 (rainbow-delimiters-depth-4-face :inherit outline-3)
 (rainbow-delimiters-depth-5-face :inherit outline-6)
 (rainbow-delimiters-depth-6-face :inherit outline-2)
 (rainbow-delimiters-depth-7-face :inherit outline-5)
 (rainbow-delimiters-depth-8-face :inherit outline-1)
 (rainbow-delimiters-depth-9-face :inherit outline-4))

(provide-theme 'ate)

(provide 'ate-theme)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; ate-theme.el ends here
